export default [
  { src: 'assets/technology-logos/Logo-HTML.png', alt: 'html' },
  { src: 'assets/technology-logos/Logo-CSS3.png', alt: 'css' },
  { src: 'assets/technology-logos/Logo-JS.png', alt: 'javascript' },
  { src: 'assets/technology-logos/Logo-GIT.png', alt: 'git' },
  { src: 'assets/technology-logos/Logo-React.png', alt: 'react' },
  { src: 'assets/technology-logos/Logo-Angular.png', alt: 'angular' },
  { src: 'assets/technology-logos/Logo-React-Router.png', alt: 'react-router' },
  { src: 'assets/technology-logos/Logo-Redux.png', alt: 'redux' },
  { src: 'assets/technology-logos/Logo-Typescript.webp', alt: 'typescript' },
  { src: 'assets/technology-logos/Logo-Wordpress.png', alt: 'wordpress' },
  { src: 'assets/technology-logos/Logo-PHP.png', alt: 'PHP' },
  { src: 'assets/technology-logos/Logo-NodeJS.png', alt: 'node' },
  { src: 'assets/technology-logos/Logo-Express.png', alt: 'express' },
  { src: 'assets/technology-logos/Logo-Nest.jfif', alt: 'nest' },
  { src: 'assets/technology-logos/Logo-Sequelize.png', alt: 'sequelize' },
  { src: 'assets/technology-logos/Logo-Mysql.png', alt: 'mysql' },
  { src: 'assets/technology-logos/Logo-PostgreSQL.png', alt: 'postgresql' },
  { src: 'assets/technology-logos/Logo-HTML.png', alt: 'html' },
  { src: 'assets/technology-logos/Logo-CSS3.png', alt: 'css' },
  { src: 'assets/technology-logos/Logo-JS.png', alt: 'javascript' },
  { src: 'assets/technology-logos/Logo-GIT.png', alt: 'git' },
  { src: 'assets/technology-logos/Logo-React.png', alt: 'react' },
  { src: 'assets/technology-logos/Logo-Angular.png', alt: 'angular' },
  { src: 'assets/technology-logos/Logo-React-Router.png', alt: 'react-router' },
];
